### ISSUE TITLE
sample files for each step?

### ISSUE THREAD

**Issue by cteenis** [lh3/psmc#6]
HI, I am new to PSMC and followed the commands in the README for a test run. However, I received an error msg same as described in "#4 Rho and theta zero". I want to figure out what went wrong and one thing I can think of is to compare all the intermediate files with a "standard" sample file. Is it possible that you can add some sample files for each step? Thanks.

**Comment by willright28** [comment]
hi @cteenis , have you solved this problem? Cuz I'm having the same problem as yours...
Thanks in advance!

**Comment by cteenis** [comment]
> 
> 
> hi @cteenis , have you solved this problem? Cuz I'm having the same problem as yours...
> Thanks in advance!

Dear @willright28 , unfortunately I do not remember how exactly I solved this specific problem as I had run into several problems back then. What I can remember is that you need to use *samtools-0.1.x instead of  samtools-1.x (same for bcftools, vcftools.pl). Hope this can be helpful!

**Comment by willright28** [comment]
Thanks for the help a lot!


 
---Original---

**Comment by GabrieleNocchi** [comment]
> Thanks for the help a lot!
> […](#)
> ---Original--- From: "cteenis"<notifications@github.com&gt; Date: 2019/9/5 11:23:18 To: "lh3/psmc"<psmc@noreply.github.com&gt;; Cc: "willright28"<854751714@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [lh3/psmc] sample files for each step? (#6) hi @cteenis , have you solved this problem? Cuz I'm having the same problem as yours... Thanks in advance! Dear @willright28 , unfortunately I do not remember how exactly I solved this specific problem as I had run into several problems back then. What I can remember is that you need to use *samtools-0.1.x instead of samtools-1.x (same for bcftools, vcftools.pl). Hope this can be helpful! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Did you find a solution?

**Comment by GabrieleNocchi** [comment]
> Thanks for the help a lot!
> […](#)
> ---Original--- From: "cteenis"<notifications@github.com&gt; Date: 2019/9/5 11:23:18 To: "lh3/psmc"<psmc@noreply.github.com&gt;; Cc: "willright28"<854751714@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [lh3/psmc] sample files for each step? (#6) hi @cteenis , have you solved this problem? Cuz I'm having the same problem as yours... Thanks in advance! Dear @willright28 , unfortunately I do not remember how exactly I solved this specific problem as I had run into several problems back then. What I can remember is that you need to use *samtools-0.1.x instead of samtools-1.x (same for bcftools, vcftools.pl). Hope this can be helpful! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Did you find a solution?

**Comment by willright28** [comment]
> > Thanks for the help a lot!
> > […](#)
> > ---Original--- From: "cteenis"<[notifications@github.com](mailto:notifications@github.com)> Date: 2019/9/5 11:23:18 To: "lh3/psmc"<[psmc@noreply.github.com](mailto:psmc@noreply.github.com)>; Cc: "willright28"<[854751714@qq.com](mailto:854751714@qq.com)>;"Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; Subject: Re: [lh3/psmc] sample files for each step? (#6) hi @cteenis , have you solved this problem? Cuz I'm having the same problem as yours... Thanks in advance! Dear @willright28 , unfortunately I do not remember how exactly I solved this specific problem as I had run into several problems back then. What I can remember is that you need to use *samtools-0.1.x instead of samtools-1.x (same for bcftools, vcftools.pl). Hope this can be helpful! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Did you find a solution?

hi @GabrieleNocchi 
I tried samtools-0.1.18 and it worked.
Hope this can be helpful.
